EXE = audacity-packer.exe
RES = audacity-packer.res

include Makefile

LDFLAGS += -mwindows -municode -liup -lgdi32 -lcomdlg32 -lcomctl32 -luuid -loleaut32 -lole32
CFLAGS += -DWINVER=0x0600 -DUNICODE=1 -D_UNICODE=1

audacity-packer-installer.exe: audacity-packer.nsi audacity-packer-32.exe audacity-packer-64.exe
	makensis audacity-packer.nsi
